src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CandidatRepository::class)
 */
class Candidat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cognoms;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $telefon;

    /**
     * @ORM\ManyToOne(targetEntity=Oferta::class, inversedBy="candidats")
     */
    private $oferta;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $estudis;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCognoms(): ?string
    {
        return $this->cognoms;
    }

    public function setCognoms(?string $cognoms): self
    {
        $this->cognoms = $cognoms;

        return $this;
    }

    public function getTelefon(): ?int
    {
        return $this->telefon;
    }

    public function setTelefon(?int $telefon): self
    {
        $this->telefon = $telefon;

        return $this;
    }

    public function getOferta(): ?Oferta
    {
        return $this->oferta;
    }

    public function setOferta(?Oferta $oferta): self
    {
        $this->oferta = $oferta;

        return $this;
    }

    public function getEstudis(): ?string
    {
        return $this->estudis;
    }

    public function setEstudis(?string $estudis): self
    {
        $this->estudis = $estudis;

        return $this;
    }
}

src/Entity/Empresa.php
<?php

namespace App\Entity;

use App\Repository\EmpresaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmpresaRepository::class)
 */
class Empresa
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tipus;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $correu;

    /**
     * @ORM\OneToMany(targetEntity=Oferta::class, mappedBy="empresa")
     */
    private $ofertes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    public function __construct()
    {
        $this->ofertes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTipus(): ?string
    {
        return $this->tipus;
    }

    public function setTipus(?string $tipus): self
    {
        $this->tipus = $tipus;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getCorreu(): ?string
    {
        return $this->correu;
    }

    public function setCorreu(?string $correu): self
    {
        $this->correu = $correu;

        return $this;
    }

    /**
     * @return Collection|Oferta[]
     */
    public function getOfertes(): Collection
    {
        return $this->ofertes;
    }

    public function addOferte(Oferta $oferte): self
    {
        if (!$this->ofertes->contains($oferte)) {
            $this->ofertes[] = $oferte;
            $oferte->setEmpresa($this);
        }

        return $this;
    }

    public function removeOferte(Oferta $oferte): self
    {
        if ($this->ofertes->contains($oferte)) {
            $this->ofertes->removeElement($oferte);
            // set the owning side to null (unless already changed)
            if ($oferte->getEmpresa() === $this) {
                $oferte->setEmpresa(null);
            }
        }

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
}

src/Entity/Oferta.php
<?php

namespace App\Entity;

use App\Repository\OfertaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OfertaRepository::class)
 */
class Oferta
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descripcio;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dataPub;

    /**
     * @ORM\ManyToOne(targetEntity=Empresa::class, inversedBy="ofertes")
     */
    private $empresa;

    /**
     * @ORM\OneToMany(targetEntity=Candidat::class, mappedBy="oferta")
     */
    private $candidats;

    /**
     * @var String
     */
    private $dataPubEnString;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titol;

    public function __construct()
    {
        $this->candidats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescripcio(): ?string
    {
        return $this->descripcio;
    }

    public function setDescripcio(?string $descripcio): self
    {
        $this->descripcio = $descripcio;

        return $this;
    }

    public function getDataPub(): ?\DateTimeInterface
    {
        return $this->dataPub;
    }

    public function setDataPub(?\DateTimeInterface $dataPub): self
    {
        $this->dataPub = $dataPub;
        $this->dataPubEnString = date_format($dataPub, 'Y-m-d');

        return $this;
    }

    public function getDataPubString() : string
    {
        $this->dataPubEnString = date_format($this->dataPub, 'Y-m-d');
        return $this->dataPubEnString;
    }

    public function getEmpresa(): ?Empresa
    {
        return $this->empresa;
    }

    public function setEmpresa(?Empresa $empresa): self
    {
        $this->empresa = $empresa;

        return $this;
    }

    /**
     * @return Collection|Candidat[]
     */
    public function getCandidats(): Collection
    {
        return $this->candidats;
    }

    public function addCandidat(Candidat $candidat): self
    {
        if (!$this->candidats->contains($candidat)) {
            $this->candidats[] = $candidat;
            $candidat->setOferta($this);
        }

        return $this;
    }

    public function removeCandidat(Candidat $candidat): self
    {
        if ($this->candidats->contains($candidat)) {
            $this->candidats->removeElement($candidat);
            // set the owning side to null (unless already changed)
            if ($candidat->getOferta() === $this) {
                $candidat->setOferta(null);
            }
        }

        return $this;
    }

    public function getTitol(): ?string
    {
        return $this->titol;
    }

    public function setTitol(?string $titol): self
    {
        $this->titol = $titol;

        return $this;
    }
}

src/Controller/EmpresaController.php
<?php

namespace App\Controller;

use App\Entity\Empresa;
use App\Entity\Oferta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class EmpresaController extends AbstractController
{
    /**
     * @Route("/empresa", name="empresa")
     */
    public function index()
    {
        $empreses = $this->getDoctrine()->getRepository(Empresa::class)->findAll();

        return $this->render('empresa/index.html.twig', ['empreses' => $empreses]);
    }
}

src/Controller/OfertaController.php
<?php

namespace App\Controller;

use App\Entity\Oferta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class OfertaController extends AbstractController
{
    /**
     * @Route("/index", name="index")
     */
    public function index()
    {
        $ofertes = $this->getDoctrine()->getRepository(Oferta::class)->findAll();

        return $this->render('oferta/index.html.twig', ['ofertes' => $ofertes]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Inici - Job Or Work {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    {% block stylesheets %}{% endblock %}

</head>
<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Job Or Work</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('index') }}">Inici <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('empresa') }}">Empreses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('index') }}">Ofertes</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block body %}
        <div class="container">
            <h2>LLISTA OFERTES</h2>

            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Titol</th>
                        <th scope="col">Descripcio</th>
                        <th scope="col">Data </th>
                        <th scope="col">Empresa</th>
                        <th scope="col">Detalls</th>
                    </tr>
                </thead>
                <tbody>
                {% for oferta in ofertes %}
                    <tr>
                        <td>{{ oferta.id }}</td>
                        <td>{{ oferta.descripcio }}</td>
                        <td>{{ oferta.dataPubString }}</td>
                        <td>{{ oferta.empresa.nom }}</td>
                        <td>
                            <button type="button" class="btn btn-primary"> Detall </button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endblock %}
    {% block javascripts %}{% endblock %}

</body>
</html>

templates/empresa/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Empreses - Job Or Work{% endblock %}

{% block body %}
    <div class="container">
        <h2>LLISTA EMPRESAS</h2>

        <table class="table table-dark">
            <thead>
            <tr>
                <th class="text-center" scope="col">ID</th>
                <th class="text-center" scope="col">Tipus</th>
                <th class="text-center" scope="col">Logo</th>
                <th class="text-center" scope="col">Correu</th>
                <th class="text-center" scope="col">Nom</th>
                <th class="text-center" scope="col">Detalls</th>
            </tr>
            </thead>
            <tbody>
            {% for empresa in empresas %}
                <tr>
                    <td>{{ empresa.id }}</td>
                    <td>{{ empresa.tipus }}</td>
                    <td>{{ empresa.logo }}</td>
                    <td>{{ empresa.correu }}</td>
                    <td>{{ empresa.nom }}</td>
                    <td>
                        <button type="button" class="btn btn-primary"> Detall </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/oferta/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inici - Job or Work{% endblock %}

{% block body %}

{% endblock %}